# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DayOneToHugo < Formula
  desc "Converts Day One JSON exports to a Hugo site"
  homepage "https://day-one-to-hugo.lmika.dev/"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/lmika/day-one-to-hugo/releases/download/v1.0.0/day-one-to-hugo_1.0.0_darwin_amd64.tar.gz"
      sha256 "3d926006017da7c8f95e017ba3321bbc7cff5eca6c0f13f149fbde65f5a52a59"

      def install
        bin.install "day-one-to-hugo"
      end
    end
    on_arm do
      url "https://github.com/lmika/day-one-to-hugo/releases/download/v1.0.0/day-one-to-hugo_1.0.0_darwin_arm64.tar.gz"
      sha256 "10bc7afa416540364d8510200a8fa1aa38b3d57d60f649b2158ba92bbe5e130a"

      def install
        bin.install "day-one-to-hugo"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lmika/day-one-to-hugo/releases/download/v1.0.0/day-one-to-hugo_1.0.0_linux_amd64.tar.gz"
        sha256 "f4e2b0a994b0c6d926a65b5b3a92af58ae80f965722df669644f8625cc664094"

        def install
          bin.install "day-one-to-hugo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lmika/day-one-to-hugo/releases/download/v1.0.0/day-one-to-hugo_1.0.0_linux_arm64.tar.gz"
        sha256 "2b5bdb9170b376ce794bb273d4d114fdb4b0391c9057177de044689d2aab9267"

        def install
          bin.install "day-one-to-hugo"
        end
      end
    end
  end
end
