# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DayOneToHugo < Formula
  desc "Converts Day One JSON exports to a Hugo site"
  homepage "https://day-one-to-hugo.lmika.dev/"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/lmika/day-one-to-hugo/releases/download/v0.1.1/day-one-to-hugo_0.1.1_darwin_amd64.tar.gz"
      sha256 "9b9aabc27203219c3c04ea7a0ce1131361f60f85c2f5975819c1054d05c5ac24"

      def install
        bin.install "day-one-to-hugo"
      end
    end
    on_arm do
      url "https://github.com/lmika/day-one-to-hugo/releases/download/v0.1.1/day-one-to-hugo_0.1.1_darwin_arm64.tar.gz"
      sha256 "0f25cf9febd3b0aa67f5c6bc2c10ce49f8a931686fd0168f88ef7426ea86d979"

      def install
        bin.install "day-one-to-hugo"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lmika/day-one-to-hugo/releases/download/v0.1.1/day-one-to-hugo_0.1.1_linux_amd64.tar.gz"
        sha256 "62672d04300170ff2de8b960c207d88e0b68d9fd50fc2eb62cb01495e171964f"

        def install
          bin.install "day-one-to-hugo"
        end
      end
    end
  end
end
